spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huuquannguyen/th2501-properties.git
encrypt:
  key: secretkey
server:
  port: 8071